version: 2.1

commands:
  env_setup:
    description: Environment Setup
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Dependencies
          command: |
            sudo sh -c 'echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list'
            sudo apt-get update
            sudo apt-get install -y protobuf-compiler/stretch-backports cmake golang curl
            sudo apt-get clean
            sudo rm -r /var/lib/apt/lists/*
            rustup component add clippy rustfmt
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=myapp' >> $BASH_ENV

jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    resource_class: 2xlarge
    steps:
      - env_setup
      - run:
          name: Git Hooks and Checks
          command: ./scripts/git-checks.sh
      - run:
          name: Linting
          command: |
            ./scripts/nightly_features.sh
  terraform:
    docker:
      - image: hashicorp/terraform
    resource_class: small
    steps:
      - checkout
      - run:
          name: Terraform init
          command: terraform init
          working_directory: terraform/
      - run:
          name: Terraform validate
          command: terraform validate
          working_directory: terraform/

workflows:
  commit-workflow:
    jobs:
      - build
      - terraform
